#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:1be415750ceedab56882235e1f74f6570a29e4ee103b2c75b39467ce3288899b
  - image: gcr.io/paketo-community/python@sha256:1228cfb8003f830b178b9b8a227889cae32df1aed74a746f2ac59b6bb8e88961
  - image: gcr.io/paketo-buildpacks/java@sha256:d7bda53204657210b4e60880b9fc2ef116716e9d8baf06618c5321c60daa5a69
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:efb5d165782a11f9469e396174991a4eab09cf812be54d6b318b3f34e60b69fe
  - image: gcr.io/paketo-buildpacks/go@sha256:6a4fa7bb587fedeb0a3ba89c6a2bb2ab4f0787c16867b6645f251e50708a2121
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:edaaa642a78b83a795e795ead0f0bb70413951d42238f92400b0c3e714e610d7
  - image: gcr.io/paketo-buildpacks/php@sha256:c62973db4ff5b876e634409f038b6962a45d3454ff29fba5cf56b703d00c7ef3
  - image: gcr.io/paketo-buildpacks/procfile@sha256:228e56228872d5033290bfb2e6d3d8d9def04e3d2f7a542aa04b0a7c642832b0

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:3261bf42edbf0f3060cfb4ca8b15fee4153eb64624335e882c1138d6bfafb128"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:138901ade32d7f0c2b302ed362a9f8f78552d095d67c4d1ed5e63c4a44d64a89"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
