#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:1be415750ceedab56882235e1f74f6570a29e4ee103b2c75b39467ce3288899b
  - image: gcr.io/paketo-community/python@sha256:1228cfb8003f830b178b9b8a227889cae32df1aed74a746f2ac59b6bb8e88961
  - image: gcr.io/paketo-buildpacks/java@sha256:b19018e7fee5b6f9bd8d8306d89547a50c57b92f5426b3f8a28f19b813542add
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:105546a44e71067433a077e69a59b10da2f3f0cbbe73d7d6bb05d655ee9fe10f
  - image: gcr.io/paketo-buildpacks/go@sha256:6a4fa7bb587fedeb0a3ba89c6a2bb2ab4f0787c16867b6645f251e50708a2121
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:22169509b97db7c66bda0f43dde24838d6ba0e5b7e18867d2ab3af1035062834
  - image: gcr.io/paketo-buildpacks/php@sha256:c62973db4ff5b876e634409f038b6962a45d3454ff29fba5cf56b703d00c7ef3
  - image: gcr.io/paketo-buildpacks/procfile@sha256:c033da1182bc34472ee8f3bc2f68f13775ef9a3d4b9f170e3bfb316d099ca497

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:fd33db2afcf9faafa120357c8b5233a5215a5d044ad994d5bed224d9b36e8242"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:1bb47ce400a74248f1c3cca186b3091d887ab48329025c3fcd33dc9d4675f7f0"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
