#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:809b928072fbc8a33508081d1f1bce43cbdf21a01bf084d2bd960af94128ee7d
  - image: gcr.io/paketo-community/python@sha256:fc28df8bd74dd67dd865e73f162f08e78ddcc4ac4f42834e15d3c4eb7714007b
  - image: gcr.io/paketo-buildpacks/java@sha256:9f025c5c1a3a490f7681d5cb23be642a705423126b33dde1338284faf2fe09fe
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:9887bb6b7d0c410ccdf6fa940658dddecfce5ded1ac5696ced608c78649594b3
  - image: gcr.io/paketo-buildpacks/go@sha256:57b2c4aed579f88bd0a2c6875885d3625511d652018ddffd52f97512dc17f5eb
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:e6f981076c7d374be2bdddd86fb5c4d0fa2f5a922080769714c3d1598c4adf2f
  - image: gcr.io/paketo-buildpacks/php@sha256:db6291138c4b1ce33e15079ea3a38144147c86b8067d4fb7d3c85c746860a35d
  - image: gcr.io/paketo-buildpacks/procfile@sha256:cc3910850249adb0b7b2f6850a362dbfbfad1df976b8736ac2c90ff70093fb4e

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:4b70ed1f27dd844b6a13279e76a94ab219bc89973ec6f8ade2f8c07919a9e356"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:691eb052281456ab5b5a62d1a0e5a67bf7246783565bbecd239c5c9cf1bf51ec"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
