#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:19254ce071ad2139309280e0f88f19f7b44ff58e684c6ac834f48d1b87b946d5
  - image: gcr.io/paketo-community/python@sha256:1228cfb8003f830b178b9b8a227889cae32df1aed74a746f2ac59b6bb8e88961
  - image: gcr.io/paketo-buildpacks/java@sha256:8b0efb468411929005ddae01fdc9143f247f45f6de7a513dc7fab047fcb3e8a9
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:34813ead861ab5a6d98d45d244006e5122c47a7c0e714f524566fa916f2dd529
  - image: gcr.io/paketo-buildpacks/go@sha256:077aeb6e0f3e4f648b935ef584d07028e3df894cdff3cbc68cdab1d42b57781c
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:0e94d7990b625a2224a35207f66229aecd146b901d102a501d31f1aefd85cff5
  - image: gcr.io/paketo-buildpacks/php@sha256:789c30e6f6d9bb49e7da0c2c924ce94d187485ee36fe917fd7fe951d0079246a
  - image: gcr.io/paketo-buildpacks/procfile@sha256:68aa25bd61299e91b8df1d99ed88e90365edc05bfb17e71828880b42c6da2ddb

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:f3c1ee4a00414dd75b4f500747722e2dae433ea269bf281095a87fa127b5f84c"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:38cb32a6f7dd138b7910e64d97bd527c0bf933db3acec0cabd1d5548629098be"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
